FROM nginx

RUN apt update && apt install -y bash

RUN curl -sL https://deb.nodesource.com/setup_14.x | bash - \
    && apt-get install -y nodejs \
    && npm i npm@latest -g

ENV APP_PATH /usr/src/front

WORKDIR $APP_PATH

COPY package.json package-lock.json $APP_PATH/

RUN npm ci