version: '3.1'

services: 

    db:
        image: github.com/isandroazedo/device-management-db
        command: --default-authentication-plugin=mysql_native_password
        environment: 
            MYSQL_ROOT_PASSWORD: pwd121212
        volumes: 
            - ./datadir:/var/lib/mysql
        ports:
            - 3306:3306
        
    api:
        image: github.com/isandroazedo/device-management-api
        depends_on: 
            - db
        ports:
            - 8000:8000
    
    web:
        image: github.com/isandroazedo/device-management-web
        depends_on: 
            - api
        ports:
            - 80:80
